spring:
  jpa:
    hibernate:
      ddl-auto: validate
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: "jdbc:h2:file:./db/db_file"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
  h2:
    console:
      enabled: true
      path: /h2
